### ISSUE TITLE
Ability to filter output by log level

### ISSUE THREAD

**Issue by evant** [ZacSweers/kotlin-compile-testing#198]
In switching to this from `room-compiler-processing-testing`. One thing I miss is that it stored messages by `Diagnostic.Kind` so I can get ex, only the errors, or only the warnings. Looking at the implementation it seems like this info may be available from `org.jetbrains.kotlin.cli.common.messages.MessageCollector`

for now, I can filter lines by the added "v:", "w:" or "e:" prefix but it would be nice to have something more official.

**Comment by ZacSweers** [comment]
Sorry just now seeing this. Have a suggested API?

**Comment by evant** [comment]
No strong opinions, but you could use https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-work-release/room/room-compiler-processing-testing/src/main/java/androidx/room/compiler/processing/util/DiagnosticMessage.kt as inspiration

**Comment by ZacSweers** [comment]
Will be in 0.5.0 and implemented in #196. API will be like so

```kotlin
compilation.kspLogginLevels = EnumSet.of(CompilerMessageSeverity.ERROR, CompilerMessageSeverity.INFO, ...)
```

**Comment by evant** [comment]
Finally got around to testing this. One downside of the current implementation is that you have to decide what to filter beforehand instead of after the fact. For example, before I was throwing an exception with the contents of error but logging other output otherwise.

**Comment by evant** [comment]
If you'd be interested I might put up a pr that more-or-less copies https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-work-release/room/room-compiler-processing-testing/src/main/java/androidx/room/compiler/processing/util/compiler/DiagnosticsMessageCollector.kt

**Comment by ZacSweers** [comment]
Game 👍

**Comment by evant** [comment]
done!
