### ISSUE TITLE
Kotlin 1.9.24

### ISSUE THREAD

**Issue by tokazio** [ZacSweers/kotlin-compile-testing#251]
For when the upgrade to Kotlin 1.9.24 is planned please ?

**Comment by ZacSweers** [comment]
1.9.24 doesn't require a new release of this library to work. Couple other notes:

- Please use the Q&A section of discussions to ask questions, this is the issue tracker. https://github.com/ZacSweers/kotlin-compile-testing/discussions/categories/q-a
- In general, it's considered rude to ask for ETAs for releases in OSS projects. Especially without a specific need for one like this.
