### ISSUE TITLE
`com.sun.tools.javac.util.Context` class can't be found 

### ISSUE THREAD

**Issue by mars885** [ZacSweers/kotlin-compile-testing#277]
Greetings.

I'm in a process of [migrating my lib](https://github.com/mars885/hilt-binder/pull/51) to the Kotlin 2.0 version and I've stumbled upon a blocker where my Java annotation processor's tests fail (both locally and on CI) with the following message:
```
e: [kapt] 'com.sun.tools.javac.util.Context' class can't be found ('tools.jar' is absent in the plugin classpath). Kapt won't work.
```

The following env & dependencies are used for tests:
- Kotlin: 2.0.0
- KSP: 2.0.0-1.0.24
- `dev.zacsweers.kctfork:ksp:0.5.1`
- JDK: `corretto-1.8.0_412`
- kapt4: `false`

The testing lib is set up like this:
```kotlin
private fun setupCompilation(
    sourceFiles: List<SourceFile>,
    processorType: ProcessorType,
): KotlinCompilation {
    val compilation = KotlinCompilation().apply {
        sources = sourceFiles
        verbose = false
        inheritClassPath = true
        languageVersion = "1.9"

        when (processorType) {
            ProcessorType.JAVAC -> annotationProcessors = listOf(HiltBinderJavacProcessor())
            ProcessorType.KSP -> configureKsp {
                symbolProcessorProviders.add(HiltBinderKspProcessor.Provider())
            }
        }
    }

    return compilation
}
```

The `jdkHome` and `toolsJar` properties from the `KotlinCompilation` class resolve to the correct paths when debugging:
- jdkHome -> `/Users/paul/Library/Java/JavaVirtualMachines/corretto-1.8.0_412/Contents/Home`
- toolsJar -> `/Users/paul/Library/Java/JavaVirtualMachines/corretto-1.8.0_412/Contents/Home/lib/tools.jar`

I've also verified that `tools.jar` does in fact exists in the path `/Users/paul/Library/Java/JavaVirtualMachines/corretto-1.8.0_412/Contents/Home/lib/tools.jar`.

Do you have an idea what's causing this? I've searched the Internet for answers, but nothing worked in my case.

**Comment by ZacSweers** [comment]
This is documented in the readme: https://github.com/ZacSweers/kotlin-compile-testing?tab=readme-ov-file#java-16-compatibility
