### ISSUE TITLE
Unresolved references

### ISSUE THREAD

**Issue by GuilhE** [ZacSweers/kotlin-compile-testing#302]
[This test](https://github.com/GuilhE/KMP-ComposeUIViewController/blob/b40cc0de84ee2875eb709a955d93d253774626f2/kmp-composeuiviewcontroller-ksp/src/test/kotlin/composeuiviewcontroller/ProcessorTest.kt#L56) will fail:

```
val code = """
    package com.mycomposable.test
        
    data class ViewState(val field: Int)
    
    @Composable
    fun ScreenA(state: ViewState) { }
""".trimIndent()
```

With `Unresolved reference 'Composable'` or any other I put in the test class. Can we somehow make it ignore the references? I was using `tschuchort` library and this was not an issue, only when I switched to yours. This happens with or without the ksp2 enabled.

Thanks!

**Comment by ZacSweers** [comment]
This is a library for testing compilations and that test does not compile. You need to import the composable annotation

**Comment by GuilhE** [comment]
> This is a library for testing compilations and that test does not compile. You need to import the composable annotation

When I add `import androidx.compose.runtime.Composable` it throws  `Unresolved reference` for `androidx`. I other tests where I import my custom annotations, and I import them, it also throws unresolved. Example:

```
val code = """
            package com.mycomposable.test
            
            import $composeUIViewControllerStateAnnotationName 
            import import androidx.compose.runtime.Composable
            
            private data class ViewState(val field: Int)
            
            @Composable
            private fun ScreenA(state: ViewState) { }
            
            @Composable
            private fun ScreenB(@ComposeUIViewControllerState state: ViewState) { }
        """.trimIndent()
```
        
all this imports fail.

**Comment by GuilhE** [comment]
Well, if I only compare the output files (generated) with what I expect, it works, as long as I don't assert the exitCode.

`//assertEquals(KotlinCompilation.ExitCode.OK, result.exitCode)`

Does it make sense ignore it? 🤔
